version: '3'

services:
    clickhouse-zookeeper:
        image: zookeeper:3.8.2
        ports:
            - 22181:2181
            - 22182:2182
            - 20000:22
        container_name: clickhouse-zookeeper
        hostname: clickhouse-zookeeper
        # command: ["/bin/bash", "-c", "apt-get update", "apt-get install -y openssh-server", "mkdir -p /var/run/sshd", "/usr/sbin/sshd -D &"]

    clickhouse-01:
        image: yandex/clickhouse-server
        hostname: clickhouse-01
        container_name: clickhouse-01
        ports:
            - 9001:9000
            - 20001:22
            - 8121:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-01:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"
        # command: ["/bin/bash", "-c", "apt-get update", "apt-get install -y openssh-server", "mkdir -p /var/run/sshd", "/usr/sbin/sshd -D &"]

    clickhouse-02:
        image: yandex/clickhouse-server
        hostname: clickhouse-02
        container_name: clickhouse-02
        ports:
            - 9002:9000
            - 20002:22
            - 8122:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-02.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-02:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"
        # command: ["/bin/bash", "-c", "apt-get update", "apt-get install -y openssh-server", "mkdir -p /var/run/sshd", "/usr/sbin/sshd -D &"]

    clickhouse-03:
        image: yandex/clickhouse-server
        hostname: clickhouse-03
        container_name: clickhouse-03
        ports:
            - 9003:9000
            - 20003:22
            - 8123:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-03.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-03:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"
        # command: ["/bin/bash", "-c", "apt-get update", "apt-get install -y openssh-server", "mkdir -p /var/run/sshd", "/usr/sbin/sshd -D &"]

    clickhouse-04:
        image: yandex/clickhouse-server
        hostname: clickhouse-04
        container_name: clickhouse-04
        ports:
            - 9004:9000
            - 20004:22
            - 8124:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-04.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-04:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"
        # command: ["/bin/bash", "-c", "apt-get update", "apt-get install -y openssh-server", "mkdir -p /var/run/sshd", "/usr/sbin/sshd -D &"]

    clickhouse-05:
        image: yandex/clickhouse-server
        hostname: clickhouse-05
        container_name: clickhouse-05
        ports:
            - 9005:9000
            - 20005:22
            - 8125:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-05.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-05:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"
        # command: ["/bin/bash", "-c", "apt-get update", "apt-get install -y openssh-server", "mkdir -p /var/run/sshd", "/usr/sbin/sshd -D &"]

    clickhouse-06:
        image: yandex/clickhouse-server
        hostname: clickhouse-06
        container_name: clickhouse-06
        ports:
            - 9006:9000
            - 20006:22
            - 8126:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-06.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-06:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"
        # command: ["/bin/bash", "-c", "apt-get update", "apt-get install -y openssh-server", "mkdir -p /var/run/sshd", "/usr/sbin/sshd -D &"]
        
    # with chproxy
    clickhouse-proxy:
        image: contentsquareplatform/chproxy:1.17.2
        hostname: chproxy
        container_name: chproxy
        command: -config /opt/config.yml
        ports:
            - 9090:9090
            - 20007:22
        volumes:
            - ./config/config.yml:/opt/config.yml
        depends_on:
            - "clickhouse-01"
            - "clickhouse-02"
            - "clickhouse-03"
            - "clickhouse-04"
            - "clickhouse-05"
            - "clickhouse-06"
networks:
    default:
        external:
            name: clickhouse-net
